# S3/.terraform-docs.yml
version: "0.15"
formatter: markdown table
header-from: main.tf
sections:
  - header
  - inputs
  - outputs
  - providers
  - requirements
  - resources
output:
  file: README.md
  mode: inject
  template: |
    {{ .Header }}

    ## Inputs

    | Name | Description | Type | Default | Required |
    |------|-------------|------|---------|:--------:|
    {{- range .Inputs }}
    | {{ .Name }} | {{ .Description }} | {{ .Type }} | {{ .Default }} | {{ ternary "yes" "no" .Required }} |
    {{- end }}

    ## Outputs

    | Name | Description |
    |------|-------------|
    {{- range .Outputs }}
    | {{ .Name }} | {{ .Description }} |
    {{- end }}
